ALTER TABLE withdraw ADD COLUMN type VARCHAR(8) NOT NULL DEFAULT 'USER';
ALTER TABLE withdraw ADD COLUMN created_by UUID NOT NULL DEFAULT 'a130116b-612c-4dfe-9684-bba664b4f602';
ALTER TABLE withdraw RENAME COLUMN user_uuid TO owner_uuid;
